# Read the Docs configuration file

# Required
version: 2

# Build documentation in the doc/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Optionally set the env required to build your docs
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt